// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type DType byte

const (
	DTypeFP32   DType = 0
	DTypeINT32  DType = 1
	DTypeUINT32 DType = 2
	DTypeBF16   DType = 3
	DTypeINT16  DType = 4
	DTypeUINT16 DType = 5
	DTypeINT8   DType = 6
	DTypeUINT8  DType = 7
)

var EnumNamesDType = map[DType]string{
	DTypeFP32:   "FP32",
	DTypeINT32:  "INT32",
	DTypeUINT32: "UINT32",
	DTypeBF16:   "BF16",
	DTypeINT16:  "INT16",
	DTypeUINT16: "UINT16",
	DTypeINT8:   "INT8",
	DTypeUINT8:  "UINT8",
}

var EnumValuesDType = map[string]DType{
	"FP32":   DTypeFP32,
	"INT32":  DTypeINT32,
	"UINT32": DTypeUINT32,
	"BF16":   DTypeBF16,
	"INT16":  DTypeINT16,
	"UINT16": DTypeUINT16,
	"INT8":   DTypeINT8,
	"UINT8":  DTypeUINT8,
}

func (v DType) String() string {
	if s, ok := EnumNamesDType[v]; ok {
		return s
	}
	return "DType(" + strconv.FormatInt(int64(v), 10) + ")"
}
