// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type MinorVersion byte

const (
	MinorVersionvalue MinorVersion = 4
)

var EnumNamesMinorVersion = map[MinorVersion]string{
	MinorVersionvalue: "value",
}

var EnumValuesMinorVersion = map[string]MinorVersion{
	"value": MinorVersionvalue,
}

func (v MinorVersion) String() string {
	if s, ok := EnumNamesMinorVersion[v]; ok {
		return s
	}
	return "MinorVersion(" + strconv.FormatInt(int64(v), 10) + ")"
}
