// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PostProcessHints struct {
	_tab flatbuffers.Table
}

func GetRootAsPostProcessHints(buf []byte, offset flatbuffers.UOffsetT) *PostProcessHints {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PostProcessHints{}
	x.Init(buf, n+offset)
	return x
}

func FinishPostProcessHintsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPostProcessHints(buf []byte, offset flatbuffers.UOffsetT) *PostProcessHints {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PostProcessHints{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPostProcessHintsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PostProcessHints) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PostProcessHints) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PostProcessHints) DoneSoftmax() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PostProcessHints) MutateDoneSoftmax(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func PostProcessHintsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PostProcessHintsAddDoneSoftmax(builder *flatbuffers.Builder, doneSoftmax bool) {
	builder.PrependBoolSlot(0, doneSoftmax, false)
}
func PostProcessHintsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
