// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type QuantType byte

const (
	QuantTypeNONE      QuantType = 0
	QuantTypeBF16      QuantType = 1
	QuantTypeINT8_SYM  QuantType = 2
	QuantTypeINT8_ASYM QuantType = 3
)

var EnumNamesQuantType = map[QuantType]string{
	QuantTypeNONE:      "NONE",
	QuantTypeBF16:      "BF16",
	QuantTypeINT8_SYM:  "INT8_SYM",
	QuantTypeINT8_ASYM: "INT8_ASYM",
}

var EnumValuesQuantType = map[string]QuantType{
	"NONE":      QuantTypeNONE,
	"BF16":      QuantTypeBF16,
	"INT8_SYM":  QuantTypeINT8_SYM,
	"INT8_ASYM": QuantTypeINT8_ASYM,
}

func (v QuantType) String() string {
	if s, ok := EnumNamesQuantType[v]; ok {
		return s
	}
	return "QuantType(" + strconv.FormatInt(int64(v), 10) + ")"
}
