// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type RoutineType byte

const (
	RoutineTypeTPU RoutineType = 0
	RoutineTypeCPU RoutineType = 1
)

var EnumNamesRoutineType = map[RoutineType]string{
	RoutineTypeTPU: "TPU",
	RoutineTypeCPU: "CPU",
}

var EnumValuesRoutineType = map[string]RoutineType{
	"TPU": RoutineTypeTPU,
	"CPU": RoutineTypeCPU,
}

func (v RoutineType) String() string {
	if s, ok := EnumNamesRoutineType[v]; ok {
		return s
	}
	return "RoutineType(" + strconv.FormatInt(int64(v), 10) + ")"
}
