// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type SectionType byte

const (
	SectionTypeWEIGHT       SectionType = 0
	SectionTypeCMDBUF       SectionType = 1
	SectionTypeFUNC_X86     SectionType = 2
	SectionTypeFUNC_AARCH64 SectionType = 3
	SectionTypeDMABUF       SectionType = 4
)

var EnumNamesSectionType = map[SectionType]string{
	SectionTypeWEIGHT:       "WEIGHT",
	SectionTypeCMDBUF:       "CMDBUF",
	SectionTypeFUNC_X86:     "FUNC_X86",
	SectionTypeFUNC_AARCH64: "FUNC_AARCH64",
	SectionTypeDMABUF:       "DMABUF",
}

var EnumValuesSectionType = map[string]SectionType{
	"WEIGHT":       SectionTypeWEIGHT,
	"CMDBUF":       SectionTypeCMDBUF,
	"FUNC_X86":     SectionTypeFUNC_X86,
	"FUNC_AARCH64": SectionTypeFUNC_AARCH64,
	"DMABUF":       SectionTypeDMABUF,
}

func (v SectionType) String() string {
	if s, ok := EnumNamesSectionType[v]; ok {
		return s
	}
	return "SectionType(" + strconv.FormatInt(int64(v), 10) + ")"
}
