// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import "strconv"

type SubMinorVersion byte

const (
	SubMinorVersionvalue SubMinorVersion = 0
)

var EnumNamesSubMinorVersion = map[SubMinorVersion]string{
	SubMinorVersionvalue: "value",
}

var EnumValuesSubMinorVersion = map[string]SubMinorVersion{
	"value": SubMinorVersionvalue,
}

func (v SubMinorVersion) String() string {
	if s, ok := EnumNamesSubMinorVersion[v]; ok {
		return s
	}
	return "SubMinorVersion(" + strconv.FormatInt(int64(v), 10) + ")"
}
