// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TpuRoutine struct {
	_tab flatbuffers.Table
}

func GetRootAsTpuRoutine(buf []byte, offset flatbuffers.UOffsetT) *TpuRoutine {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TpuRoutine{}
	x.Init(buf, n+offset)
	return x
}

func FinishTpuRoutineBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTpuRoutine(buf []byte, offset flatbuffers.UOffsetT) *TpuRoutine {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TpuRoutine{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTpuRoutineBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TpuRoutine) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TpuRoutine) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TpuRoutine) CmdbufSection() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TpuRoutine) DmabufSection() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TpuRoutineStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TpuRoutineAddCmdbufSection(builder *flatbuffers.Builder, cmdbufSection flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(cmdbufSection), 0)
}
func TpuRoutineAddDmabufSection(builder *flatbuffers.Builder, dmabufSection flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dmabufSection), 0)
}
func TpuRoutineEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
