// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cpu_op

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoolAttr struct {
	_tab flatbuffers.Table
}

func GetRootAsBoolAttr(buf []byte, offset flatbuffers.UOffsetT) *BoolAttr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoolAttr{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoolAttrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoolAttr(buf []byte, offset flatbuffers.UOffsetT) *BoolAttr {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoolAttr{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoolAttrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoolAttr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoolAttr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoolAttr) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoolAttr) Value() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BoolAttr) MutateValue(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func BoolAttrStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BoolAttrAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func BoolAttrAddValue(builder *flatbuffers.Builder, value bool) {
	builder.PrependBoolSlot(1, value, false)
}
func BoolAttrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
