// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cpu_op

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FloatArrayAttr struct {
	_tab flatbuffers.Table
}

func GetRootAsFloatArrayAttr(buf []byte, offset flatbuffers.UOffsetT) *FloatArrayAttr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FloatArrayAttr{}
	x.Init(buf, n+offset)
	return x
}

func FinishFloatArrayAttrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFloatArrayAttr(buf []byte, offset flatbuffers.UOffsetT) *FloatArrayAttr {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FloatArrayAttr{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFloatArrayAttrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FloatArrayAttr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FloatArrayAttr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FloatArrayAttr) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FloatArrayAttr) Value(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *FloatArrayAttr) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FloatArrayAttr) MutateValue(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func FloatArrayAttrStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FloatArrayAttrAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func FloatArrayAttrAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func FloatArrayAttrStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FloatArrayAttrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
